package dk.frankbille.mysqldumper.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import dk.frankbille.mysqldumper.Configuration;
import dk.frankbille.mysqldumper.sql.MysqlBinaryClient;

import javax.swing.*;
import java.awt.*;

public class SelectMysqlBinDirectoryWindow extends JDialog {
    private final MysqlBinaryClient mysqlClient;
    private JPanel contentPane;
    private JButton okButton;
    private JTextField mysqlBinDirField;
    private JButton mysqlBinDirButton;
    private JLabel testLabel;

    public SelectMysqlBinDirectoryWindow(Configuration configuration) {
        mysqlClient = new MysqlBinaryClient(configuration);
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(okButton);

        mysqlBinDirField.getDocument().addDocumentListener(new PersistedDocumentListener() {
            @Override
            protected void doSaveChanges(String text) {
                configuration.setMysqlBinDirectory(text);
                testMysqlBinDirectory();
            }
        });
        setMysqlBinDirectory(configuration.getMysqlBinDirectory());

        mysqlBinDirButton.addActionListener(e -> {
            JFileChooser selectMysqlBinDirectory = new JFileChooser(mysqlBinDirField.getText());
            selectMysqlBinDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            selectMysqlBinDirectory.setMultiSelectionEnabled(false);
            if (selectMysqlBinDirectory.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                setMysqlBinDirectory(selectMysqlBinDirectory.getSelectedFile().getAbsolutePath());
            }
        });
        okButton.addActionListener(e -> {
            dispose();
        });
    }

    private void setMysqlBinDirectory(String mysqlBinDirectory) {
        mysqlBinDirField.setText(mysqlBinDirectory);
    }

    private void testMysqlBinDirectory() {
        if (mysqlClient.isValidMysqlBinDirectory()) {
            testLabel.setText("Valid path");
            testLabel.setForeground(Color.GREEN);
            okButton.setEnabled(true);
        } else {
            testLabel.setText("Invalid path");
            testLabel.setForeground(Color.RED);
            okButton.setEnabled(false);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FormLayout("fill:d:grow", "center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8), null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow"));
        CellConstraints cc = new CellConstraints();
        contentPane.add(panel1, cc.xy(1, 3));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        panel1.add(panel2, cc.xy(3, 1));
        okButton = new JButton();
        okButton.setText("Close");
        panel2.add(okButton, cc.xy(1, 1));
        testLabel = new JLabel();
        testLabel.setText("");
        panel1.add(testLabel, cc.xy(1, 1));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:73px:noGrow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:grow"));
        contentPane.add(panel3, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final JLabel label1 = new JLabel();
        label1.setText("Mysql Binary Directory:");
        panel3.add(label1, cc.xyw(1, 1, 3));
        mysqlBinDirField = new JTextField();
        panel3.add(mysqlBinDirField, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        mysqlBinDirButton = new JButton();
        mysqlBinDirButton.setText("...");
        panel3.add(mysqlBinDirButton, cc.xy(3, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
